In [1]:
import numpy as np

In [2]:
ls1=[1,2,3,4,5]
ls2=[6,7,8,9,10]
ls3=[11,12,13,14,15]

In [3]:
arr=np.array([ls1,ls2,ls3])

In [4]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [6]:
arr[1:,2:4]

array([[ 8,  9],
       [13, 14]])

In [8]:
arr[:2,1:3]

array([[2, 3],
       [7, 8]])

In [9]:
arr[:,1:4]

array([[ 2,  3,  4],
       [ 7,  8,  9],
       [12, 13, 14]])